services:
  - type: web
    name: roblox-gamepass-buyer
    runtime: node
    region: oregon
    plan: free
    
    buildCommand: npm install
    startCommand: node index.js

    envVars:
      - key: ROBLOX_COOKIE
        sync: false
